### Data Manipulation and Analysis with Pandas
Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Pandas.

In [1]:
import pandas as pd

df = pd.read_csv('sales_data.csv')
# First five entries
df.head(5)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,NaN,159.42,2533654.00,1582243.50,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50

In [2]:
# last 5 entries
df.tail(5)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
95,Sub-Saharan Africa,Mali,Clothes,Online,M,7/26/2011,512878119,9/3/2011,888,109.28,35.84,97040.64,31825.92,65214.72
96,Asia,Malaysia,Fruits,Offline,L,11/11/2011,810711038,12/28/2011,6267,9.33,6.92,58471.11,43367.64,15103.47
97,Sub-Saharan Africa,Sierra Leone,Vegetables,Offline,C,6/1/2016,728815257,6/29/2016,1485,154.06,90.93,228779.10,135031.05,93748.05
98,North America,Mexico,Personal Care,Offline,M,7/30/2015,559427106,8/8/2015,5767,81.73,56.67,471336.91,326815.89,144521.02
99,Sub-Saharan Africa,Mozambique,Household,Offline,L,2/10/2012,665095412,2/15/2012,5367,668.27,502.54,3586605.09,2697132.18,889472.91

In [3]:
# statistical data
df.describe()

,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
count,1.000000e+02,100.000000,96.000000,100.000000,1.000000e+02,1.000000e+02,1.000000e+02
mean,5.550204e+08,5128.710000,271.614375,191.048000,1.373488e+06,9.318057e+05,4.416820e+05
std,2.606153e+08,2794.484562,232.011445,188.208181,1.460029e+06,1.083938e+06,4.385379e+05
min,1.146066e+08,124.000000,9.330000,6.920000,4.870260e+03,3.612240e+03,1.258020e+03
25%,3.389225e+08,2836.250000,81.730000,35.840000,2.687212e+05,1.688680e+05,1.214436e+05
50%,5.577086e+08,5382.500000,154.060000,107.275000,7.523144e+05,3.635664e+05,2.907680e+05
75%,7.907551e+08,7369.000000,437.200000,263.330000,2.212045e+06,1.613870e+06,6.358288e+05
max,9.940222e+08,9925.000000,668.270000,524.960000,5.997055e+06,4.509794e+06,1.719922e+06

In [4]:
# Data types of data
df.dtypes

Region                str
Country               str
Item Type             str
Sales Channel         str
Order Priority        str
Order Date            str
Order ID            int64
Ship Date             str
Units Sold          int64
Unit Price        float64
Unit Cost         float64
Total Revenue     float64
Total Cost        float64
Total Profit      float64
dtype: object

In [5]:
## Handling missing values
# mentions true where any entries are missing
df.isnull()
# I kept 4 entries of unit price null in csv manually to check
df.isnull().any(axis=1)
df.isnull().sum() # In which column how man entries are missing

Region            0
Country           0
Item Type         0
Sales Channel     0
Order Priority    0
Order Date        0
Order ID          0
Ship Date         0
Units Sold        0
Unit Price        4
Unit Cost         0
Total Revenue     0
Total Cost        0
Total Profit      0
dtype: int64

In [6]:
# Fill empty entries with something
df.fillna(0)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,0.00,159.42,2533654.00,1582243.50,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Sub-Saharan Africa,Mali,Clothes,Online,M,7/26/2011,512878119,9/3/2011,888,109.28,35.84,97040.64,31825.92,65214.72
96,Asia,Malaysia,Fruits,Offline,L,11/11/2011,810711038,12/28/2011,6267,9.33,6.92,58471.11,43367.64,15103.47
97,Sub-Saharan Africa,Sierra Leone,Vegetables,Offline,C,6/1/2016,728815257,6/29/2016,1485,154.06,90.93,228779.10,135031.05,93748.05
98,North America,Mexico,Personal Care,Offline,M,7/30/2015,559427106,8/8/2015,5767,81.73,56.67,471336.91,326815.89,144521.02
99,Sub-Saharan Africa,Mozambique,Household,Offline,L,2/10/2012,665095412,2/15/2012,5367,668.27,502.54,3586605.09,2697132.18,889472.91

In [7]:
## Filling missing values with the mean of the values
df['Unit_Price_fillNA'] = df['Unit Price'].fillna(df['Unit Price'].mean())
df

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Unit_Price_fillNA
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,NaN,159.42,2533654.00,1582243.50,951410.50,271.614375
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36,205.700000
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75,651.210000
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82,9.330000
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50,651.210000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Sub-Saharan Africa,Mali,Clothes,Online,M,7/26/2011,512878119,9/3/2011,888,109.28,35.84,97040.64,31825.92,65214.72,109.280000
96,Asia,Malaysia,Fruits,Offline,L,11/11/2011,810711038,12/28/2011,6267,9.33,6.92,58471.11,43367.64,15103.47,9.330000
97,Sub-Saharan Africa,Sierra Leone,Vegetables,Offline,C,6/1/2016,728815257,6/29/2016,1485,154.06,90.93,228779.10,135031.05,93748.05,154.060000
98,North America,Mexico,Personal Care,Offline,M,7/30/2015,559427106,8/8/2015,5767,81.73,56.67,471336.91,326815.89,144521.02,81.730000
99,Sub-Saharan Africa,Mozambique,Household,Offline,L,2/10/2012,665095412,2/15/2012,5367,668.27,502.54,3586605.09,2697132.18,889472.91,668.270000

In [8]:
df.dtypes

Region                   str
Country                  str
Item Type                str
Sales Channel            str
Order Priority           str
Order Date               str
Order ID               int64
Ship Date                str
Units Sold             int64
Unit Price           float64
Unit Cost            float64
Total Revenue        float64
Total Cost           float64
Total Profit         float64
Unit_Price_fillNA    float64
dtype: object

In [9]:
## Renaming Column name  (.rename())
# Syntax data.rename(columns={'PrevName': 'NewName'})

df = df.rename(columns={'Country': 'Nationality'})
df

,Region,Nationality,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Unit_Price_fillNA
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,NaN,159.42,2533654.00,1582243.50,951410.50,271.614375
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36,205.700000
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75,651.210000
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82,9.330000
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50,651.210000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Sub-Saharan Africa,Mali,Clothes,Online,M,7/26/2011,512878119,9/3/2011,888,109.28,35.84,97040.64,31825.92,65214.72,109.280000
96,Asia,Malaysia,Fruits,Offline,L,11/11/2011,810711038,12/28/2011,6267,9.33,6.92,58471.11,43367.64,15103.47,9.330000
97,Sub-Saharan Africa,Sierra Leone,Vegetables,Offline,C,6/1/2016,728815257,6/29/2016,1485,154.06,90.93,228779.10,135031.05,93748.05,154.060000
98,North America,Mexico,Personal Care,Offline,M,7/30/2015,559427106,8/8/2015,5767,81.73,56.67,471336.91,326815.89,144521.02,81.730000
99,Sub-Saharan Africa,Mozambique,Household,Offline,L,2/10/2012,665095412,2/15/2012,5367,668.27,502.54,3586605.09,2697132.18,889472.91,668.270000

In [10]:

df.dtypes

Region                   str
Nationality              str
Item Type                str
Sales Channel            str
Order Priority           str
Order Date               str
Order ID               int64
Ship Date                str
Units Sold             int64
Unit Price           float64
Unit Cost            float64
Total Revenue        float64
Total Cost           float64
Total Profit         float64
Unit_Price_fillNA    float64
dtype: object

In [11]:
## Changing datatypes (.astype())
# lets change units sold from int to float
df['New Units Sold'] = df['Units Sold'].astype(float)
df.head()

,Region,Nationality,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Unit_Price_fillNA,New Units Sold
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,NaN,159.42,2533654.00,1582243.50,951410.50,271.614375,9925.0
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36,205.700000,2804.0
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75,651.210000,1779.0
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82,9.330000,8102.0
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50,651.210000,5062.0

In [12]:
## Applying function on any data  (.apply())
df['New Value']=df['New Units Sold'].apply(lambda x:x*2)
df.head()

,Region,Nationality,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Unit_Price_fillNA,New Units Sold,New Value
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,NaN,159.42,2533654.00,1582243.50,951410.50,271.614375,9925.0,19850.0
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36,205.700000,2804.0,5608.0
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75,651.210000,1779.0,3558.0
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82,9.330000,8102.0,16204.0
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50,651.210000,5062.0,10124.0

In [14]:
## Data Aggregating And Grouping
df

,Region,Nationality,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Unit_Price_fillNA,New Units Sold,New Value
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,NaN,159.42,2533654.00,1582243.50,951410.50,271.614375,9925.0,19850.0
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36,205.700000,2804.0,5608.0
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75,651.210000,1779.0,3558.0
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82,9.330000,8102.0,16204.0
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50,651.210000,5062.0,10124.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Sub-Saharan Africa,Mali,Clothes,Online,M,7/26/2011,512878119,9/3/2011,888,109.28,35.84,97040.64,31825.92,65214.72,109.280000,888.0,1776.0
96,Asia,Malaysia,Fruits,Offline,L,11/11/2011,810711038,12/28/2011,6267,9.33,6.92,58471.11,43367.64,15103.47,9.330000,6267.0,12534.0
97,Sub-Saharan Africa,Sierra Leone,Vegetables,Offline,C,6/1/2016,728815257,6/29/2016,1485,154.06,90.93,228779.10,135031.05,93748.05,154.060000,1485.0,2970.0
98,North America,Mexico,Personal Care,Offline,M,7/30/2015,559427106,8/8/2015,5767,81.73,56.67,471336.91,326815.89,144521.02,81.730000,5767.0,11534.0
99,Sub-Saharan Africa,Mozambique,Household,Offline,L,2/10/2012,665095412,2/15/2012,5367,668.27,502.54,3586605.09,2697132.18,889472.91,668.270000,5367.0,10734.0

In [ ]:
grouped_mean = df.groupby('Region')['Unit Cost'].mean()
print(grouped_mean)

Region
Asia                                 239.587273
Australia and Oceania                154.744545
Central America and the Caribbean    157.817143
Europe                               223.166364
Middle East and North Africa         152.450000
North America                        205.293333
Sub-Saharan Africa                   183.677500
Name: Unit Cost, dtype: float64

In [17]:
# Group by two columns
grouped_sum = df.groupby(['Region','Item Type'])['Unit Cost'].sum()
print(grouped_sum)

Region                             Item Type
Asia                               Clothes              71.68
                                   Cosmetics           263.33
                                   Fruits                6.92
                                   Household          1005.08
                                   Office Supplies    1049.92
                                   Personal Care        56.67
                                   Vegetables          181.86
Australia and Oceania              Baby Food           318.84
                                   Beverages            63.58
                                   Cereal              117.11
                                   Clothes              35.84
                                   Cosmetics           263.33
                                   Fruits               13.84
                                   Meat                364.69
                                   Office Supplies     524.96
Central America and the Caribbean  Beverages            31.79
                                   Cereal              117.11
                                   Clothes              35.84
                                   Cosmetics           263.33
                                   Household           502.54
                                   Personal Care        56.67
                                   Snacks               97.44
Europe                             Baby Food           637.68
                                   Beverages            63.58
                                   Clothes             107.52
                                   Cosmetics          1316.65
                                   Household          1005.08
                                   Office Supplies    1574.88
                                   Personal Care       113.34
                                   Vegetables           90.93
Middle East and North Africa       Cereal              117.11
                                   Clothes              71.68
                                   Cosmetics           789.99
                                   Fruits               20.76
                                   Office Supplies     524.96
North America                      Household           502.54
                                   Personal Care       113.34
Sub-Saharan Africa                 Baby Food           159.42
                                   Beverages            95.37
                                   Cereal              468.44
                                   Clothes             143.36
                                   Cosmetics           526.66
                                   Fruits               27.68
                                   Household          1507.62
                                   Meat                364.69
                                   Office Supplies    2624.80
                                   Personal Care       226.68
                                   Snacks              194.88
                                   Vegetables          272.79
Name: Unit Cost, dtype: float64

In [20]:
## aggregate multiple functions
grouped_agg = df.groupby('Region')['Unit Cost'].agg(['mean', 'sum', 'count'])
grouped_agg

                                         mean      sum  count
Region
Asia                               239.587273  2635.46     11
Australia and Oceania              154.744545  1702.19     11
Central America and the Caribbean  157.817143  1104.72      7
Europe                             223.166364  4909.66     22
Middle East and North Africa       152.450000  1524.50     10
North America                      205.293333   615.88      3
Sub-Saharan Africa                 183.677500  6612.39     36

In [21]:
## Merging and joining Dataframes
df1 = pd.DataFrame({'Key':['A','B','C'], 'Value1': [1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','D'], 'Value1': [4,5,6]})

In [22]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [23]:
df2

  Key  Value1
0   A       4
1   B       5
2   D       6

In [ ]:
# Using Joins (like in DBMS)
# Merging DataFrame on the 'Key Columns' 
pd.merge(df1,df2,on="Key",how="inner")

  Key  Value1_x  Value1_y
0   A         1         4
1   B         2         5

In [25]:

pd.merge(df1,df2,on="Key",how="outer")

  Key  Value1_x  Value1_y
0   A       1.0       4.0
1   B       2.0       5.0
2   C       3.0       NaN
3   D       NaN       6.0

In [27]:

pd.merge(df1,df2,on="Key",how="left")

  Key  Value1_x  Value1_y
0   A         1       4.0
1   B         2       5.0
2   C         3       NaN

In [29]:
 
pd.merge(df1,df2,on="Key",how="right")

  Key  Value1_x  Value1_y
0   A       1.0         4
1   B       2.0         5
2   D       NaN         6