In [ ]:
# Pandas-DataFrame And Series
# Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
import pandas as pd

In [4]:
## Series
# A Pandas Series is a one-dimentional array-like object that can hold any data type. It is similar to a column in a table

import pandas as pd
data = [1,2,3,4,5]
series=pd.Series(data)
print("Series \n", series)
print(type(series))
# First are the default indexes for the data

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [5]:
## Create a series from dictionary
data = {'a':1, 'b': 2, 'c': 3}
series_dict=pd.Series(data)
print(series_dict)
# Keys will be made as index and values will be series values

a    1
b    2
c    3
dtype: int64

In [7]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [17]:
## Datafram
# A Pandas DataFrame is a two-dimensional, size-mutable, and tabular data structure with labeled axes (rows and columns).

# CSV & Text: pd.read_csv() for comma-separated values or general delimited text files.

# Excel: pd.read_excel() for .xlsx and .xls files (supports multiple sheets).

# JSON: pd.read_json() for web-based data structures.

# SQL Databases: pd.read_sql() to pull data directly from databases like PostgreSQL, MySQL, or SQLite.

## create a Dataframe from a dictionary of list

data = {   
    'Name': ['Sher', 'Hassan', 'Khan'],
    'Age': [18,19,20],
    'City': ['Quetta', 'Islamabad', 'Zhob']
} # This is basically rows and columns(2d array)

df = pd.DataFrame(data1) # This is like data in Excel Sheet
print(df)
print(type(df))

     Name  Age       City
0    Sher   20     Quetta
1  Hassan   20  Islamabad
2    Khan   20       Zhob
3     Ali   20    Karachi
<class 'pandas.DataFrame'>

In [16]:
## Create a Data frame From a list of Dictionaries

data1 = [
    {'Name': 'Sher','Age': 20, 'City': 'Quetta'},
    {'Name': 'Hassan','Age': 20, 'City': 'Islamabad'},
    {'Name': 'Khan','Age': 20, 'City': 'Zhob'},
    {'Name': 'Ali','Age': 20, 'City': 'Karachi'}
]
df1 = pd.DataFrame(data1)
print(df1)
print(type(df1))

     Name  Age       City
0    Sher   20     Quetta
1  Hassan   20  Islamabad
2    Khan   20       Zhob
3     Ali   20    Karachi
<class 'pandas.DataFrame'>

In [10]:
# Reading CSV (we can also read other formants)
df = pd.read_csv('sales_data.csv')
# Top 5 elements of df
df.head(5)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50

In [11]:
#last 5 records
df.tail(5)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
95,Sub-Saharan Africa,Mali,Clothes,Online,M,7/26/2011,512878119,9/3/2011,888,109.28,35.84,97040.64,31825.92,65214.72
96,Asia,Malaysia,Fruits,Offline,L,11/11/2011,810711038,12/28/2011,6267,9.33,6.92,58471.11,43367.64,15103.47
97,Sub-Saharan Africa,Sierra Leone,Vegetables,Offline,C,6/1/2016,728815257,6/29/2016,1485,154.06,90.93,228779.10,135031.05,93748.05
98,North America,Mexico,Personal Care,Offline,M,7/30/2015,559427106,8/8/2015,5767,81.73,56.67,471336.91,326815.89,144521.02
99,Sub-Saharan Africa,Mozambique,Household,Offline,L,2/10/2012,665095412,2/15/2012,5367,668.27,502.54,3586605.09,2697132.18,889472.91

In [21]:
### Accessing Data from Dataframe
df

     Name  Age       City
0    Sher   20     Quetta
1  Hassan   20  Islamabad
2    Khan   20       Zhob
3     Ali   20    Karachi

In [24]:
# Directly calling columns
# It will be a pandas series
df['Name']
# type(df['Name'])   #will be series

pandas.Series

In [25]:
# picking row with index using loc
df.loc[0]

Name      Sher
Age         20
City    Quetta
Name: 0, dtype: object

In [26]:
# picking column with index using loc
df.iloc[0]

Name      Sher
Age         20
City    Quetta
Name: 0, dtype: object

In [ ]:
# Picking specific using loc (using indexing)
df.loc[0, 'Name']
# usually will work, but it is generally considered bad practice and can lead to unpredictable errors
# df.loc[0, 'Name']: You are telling Pandas exactly which row label (0) and which column label ('Name') to look at in a single operation. It is fast and explicit.
# for indexing like [0, 0] iloc will be better

'Sher'

In [ ]:
# Picking specific using iloc (using indexing)
df.iloc[0, 2]

'Quetta'

In [ ]:
## Accessing a specified element (.at)
df.at[1, 'Age']  # Row index, column name (R,C)

np.int64(20)

In [36]:
## Accessing a specified element (.iat)
df.iat[1,2]

'Islamabad'

In [ ]:
# basically loc and at uses [row index, column name] format and iloc and iat uses [row index, column index]

In [ ]:
### Data Manipulation woth Dataframe
## Adding new column
df['Salary']=[50000, 60000, 70000, 80000]
df

     Name  Age       City  Salary
0    Sher   20     Quetta   50000
1  Hassan   20  Islamabad   60000
2    Khan   20       Zhob   70000
3     Ali   20    Karachi   80000

In [ ]:
## Remove a column
# df.drop('Salary') # This wont work because

#It fails because df.drop() looks for rows by default (axis 0), not columns. Since there is no row named "Salary" in your index, it throws a KeyError.

# To fix it, you must specify that you are targeting a column (axis 1):

# Option 1: df.drop('Salary', axis=1)

# Option 2 (Cleaner): df.drop(columns=['Salary'])

# Note: This returns a copy. To save the change to your variable, use df = df.drop(columns=['Salary']) or df.drop("Salary", axis=1, inplace=True)
df.drop('Salary', axis=1)

     Name  Age       City
0    Sher   20     Quetta
1  Hassan   20  Islamabad
2    Khan   20       Zhob
3     Ali   20    Karachi

In [44]:
## Add age to the column
df['Age'] = df['Age']+1
df

     Name  Age       City  Salary
0    Sher   23     Quetta   50000
1  Hassan   23  Islamabad   60000
2    Khan   23       Zhob   70000
3     Ali   23    Karachi   80000

In [ ]:
## Removing row
df.drop(3, inplace = True)
df

In [47]:
## Statistical data
df.describe()

        Age   Salary
count   3.0      3.0
mean   23.0  60000.0
std     0.0  10000.0
min    23.0  50000.0
25%    23.0  55000.0
50%    23.0  60000.0
75%    23.0  65000.0
max    23.0  70000.0